# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 21:41
from __future__ import unicode_literals

import categorias.models
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_mueble', models.CharField(choices=[('ninguno', 'Ninguno'), ('comedores', 'Comedores'), ('cocinas', 'Cocinas'), ('closets', 'Closets'), ('puertas', 'Puertas'), ('banos', 'Banos')], default='ninguno', max_length=10, verbose_name='Categoria del mueble')),
                ('imagen_categoria', sorl.thumbnail.fields.ImageField(max_length=50, upload_to=categorias.models.change_file_name, verbose_name='Foto de Categoria')),
                ('slug', models.CharField(blank=True, max_length=140, unique=True)),
            ],
            bases=(categorias.models.SlugMixin, models.Model),
        ),
    ]
